
version: 0.1.{build}

branches:
  only:
    - master

skip_non_tags: true

assembly_info:
  patch: true

configuration: Release

before_build:
  - nuget restore

build:
  project: NSuperTest.sln
  publish_nuget: true

deploy:
  provider: NuGet
  api_key:
    secure: GfdeGjw0Hl19JAeHkWGVB0HAgERXEgWOwZIbmiCrVBOas6lPbOqinzHo+FwjpC8C
  artifact: /.*\.nupkg/
