
version: 0.1.{build}

branches:
  only:
    - master

#skip_non_tags: true

assembly_info:
  patch: false

configuration: Release

before_build:
  - cmd: nuget restore

build:
  project: NSuperTest.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
